### ISSUE TITLE
Modify Gecko to load MP3 and JSON files from GitHub or web server Gecko loads from.

### ISSUE THREAD

**Issue by DougrZ** [LET-Voice-Annotation/let-gecko#18]

**Comment by DougrZ** [comment]
Modify Gecko to load MP3 and JSON files for annotation directly from either GitHub or from the let.rmati.ca web server. 
Currently a modified Gecko can be run from:

https://let.rmati.ca/gecko

The user can load data files from their local computer only.

How much effort would it take to load files from a data directory on that web server? Even better would be to load from GetHub directly so that latest committed version is always used.

Please investigate viability and report. It may be more work than is worth the effort. Just clear the assignment if this is not something you want to work on.

**Comment by DougrZ** [comment]
Hi Craig, Do you want any guidance on using Gecko? If so I wrote a few basics in this issue. [let-voice/issues/5](https://github.com/LET-Voice-Annotation/let-voice/issues/5)

**Comment by DougrZ** [comment]
Hi Craig, Gecko already has the ability to load and save from and AWS S3 storage. The free tier will allow 10GB/mth transfer, which should be enough. Each lecture is only about 25MB for both MP3 and JSON files. I'll work on adding a free S3 account.

**Comment by isohedral** [comment]
So do you want to put this aside for now? Honestly, given the relatively low number of files we'll be loading and editing, I don't mind a bit of annoyance at app startup time—most of the effort is in the annotation process itself.

I did look at around at the source code a bit. I don't think it would be too hard to add the ability to load from a folder on the host server (don't even bring up a dialog box -- just generate a list of links, one for each file on the server). But I should say that while I have some JS experience, it does extend to full-stack app development or frameworks like Angular.js (or node.js, npm, etc, etc). There are definitely aspects of the programming model that are foreign to me.

**Comment by isohedral** [comment]
I did play around with gecko a little bit, and I think I have a basic sense of what I would need to do in practice. There are probably a number of features I haven't discovered yet that would be useful.

**Comment by DougrZ** [comment]
Thanks for looking into that. I Looked into the S3 integration and it's not much help for a basic user. The files to load all have to be put straight into the URL. I do think that we'll just put both the S3 and the web server loading  ideas on hold. 

I'm just learning many of these frameworks too.

**Comment by DougrZ** [comment]
Not worth the effort right now.
